name: manage-azure-policy-aaf5930d
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'Single Subscription/Azure Policy/policies/Deploy_Service_Health_Alerts_and_corresponding_Action_Group_to_notify_of_Service_Health_Incidents_7dab5169-3ee2-4d08-acad-bfeafe94c50d/**'
#      - .github/workflows/manage-azure-policy-aaf5930d.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_aaf5930d}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          Single Subscription/Azure Policy/policies/Deploy_Service_Health_Alerts_and_corresponding_Action_Group_to_notify_of_Service_Health_Incidents_7dab5169-3ee2-4d08-acad-bfeafe94c50d/**
